



logging.level:
  root: INFO
  com.example.lab01.repository: INFO
  org.springframework.jdbc.core: INFO
  org.springframework.jdbc.core.StatementCreatorUtils: INFO
  #org.springframework.web: INFO
  #com.microsoft: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health
        
server:
  port: 7071
  
lab02:
  cache:
    host: cache
    port: 6379
    enableSsl: false
    password: password
  event:
    host: bus
    port: 5672
    username: rabbitmq
    password: rabbitmq
