
logging.level:
  root: INFO
  pe.net.tci.pse.comprobante.repository: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  #org.springframework.web: INFO
  #com.microsoft: ERROR

server:
  port: 7070
  
gcs:
  resource:
    bucket: tci-pse-storage
    
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/db01
    username: root
    password: password
  flyway:
  enabled: true
  url: jdbc:mysql://localhost:3307/db01?allowPublicKeyRetrieval=false&useSSL=true&requireSSL=true&serverTimezone=UTC&encrypt=true&autoReconnect=true
  user: root
  password: password
  locations: classpath:db/migration
#schemas: dbo
#flyway-schemas: flyway-schemas
  group: false
  cloud:
    gcp:
      stream:
      bindings:
        procesadorDeclaracionOutput:
          destination: CLIENTE-TOPIC
          group: DECLARACION
        procesadorAuditoriaOutput:
          destination: AUDITORIA-TOPIC
          group: DECLARACION
        procesadorDeclaracionInput:
          destination: CLIENTE-TOPIC
          group: DECLARACION
        procesadorAuditoriaInput:
          destination: AUDITORIA-TOPIC
          group: DECLARACION    
      project-id: tci-microservices-262022
      credentials:
        encoded-key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGNpLW1pY3Jvc2VydmljZXMtMjYyMDIyIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMGQ0OTI1MDg4OTlmOTQ2Y2YxYmU5MDcwZDA1ZGNjMDUwNDVlMDhlZSIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDMkd2Mm9EclpnYkxwVFxuV0xLNzg1TGNlSzBYandqbW1oQnFqbnZLMHNzaTdqNWpIQW9tN3dBR3FkWFVPcXU4aHBYQ2xBNXRXVXpsNXlxTVxuRzhDOUp2Q0FEZ0svclg3U0dQcVdFNmNQUngwR2hGRS83Wm83QkhkejQrMldRb0ZKbGJNMmZkZVFxcWRiZDI2UlxuVXJDTTN3N2pKdkR5ZkZJRlpuQndkdU0xajFpVTgyTU9jWTFIckpkYUt1K2xYWU1Qc3QyT2k3QUprU2NXWWo5ZlxuY0Z4WkdFc0tSbjJLd3dxU0Ivd3QxWUROREJ2LzFPM0lsWDRwdkNIbm9PUDdQSHo3UDdTdkpqelFoZXluVEt1YlxuSGlpSHFRYlBrZHRnTXoyY0N1ZEo1ZjJPM1RnOHB0U29lZU14VFRmb0diRFNEcTM3R0dtY2pIUCtqbGJPOXMrWVxuZTdhQXI2a3RBZ01CQUFFQ2dnRUFWS2kwbnVJRUdFekR6SWFTUlQyRjIzaEFwQkNyaHlVOWw0UVkrZUJJYnJ0S1xuaHFIYytGK281L0FoeC9Ia3NCYnpYWXVlTDJqU0RwbUsxcXI2VGhWaHZtNkZDWjQ3TktwSEtPa0hBOXZBR3l6OVxuWnRacm1wOUhkem1SMVFhaSsxWWNoQ3M1d1hnTXFNR2J4ZlNtdmo3ZXVXeDduSWQrVENObEIydkYwanNMWitiN1xuclp5UXhwUkZCejg4b2dnMndUYjRDUUlYMVh4cVl2SWlaRTJHMlBzMVdXYncxMy80OENqUU52a3Q1d1dzaFpSOFxuS3B6OFVVZE9rM3laZEVwMy9LQU95VVhscE1PaC84OEExKzNSWVV0SW1mNjdjRTV4anczZDNpTEt3dDNPVUlPbVxudGtFMEVKU0hhSWJpL3NESlhuVTlOeFl0NjZ6R1NUU1pJQytmY2YwZm93S0JnUURjR1FDS1pKOC9pSlRXelJ0OVxuU2VmV0RUNHhOUE43NEJkcmpFallBOEZTZThzdi80YUIvWDB4bjlGQktoeWVLaWJwYmpPbjNZVmZrVGttSDZPa1xuMi8xQnVIbm51QUFkamVoZGVTbmpIeWF4RzZETWh0ZWZyRVJtRm91RHJsRUlaUTlQUldoUzA0d3VhRHVzQk9OOFxuU2tCRWVOOElQd04vL205SFBobHlPTGhZcndLQmdRRFR6M3RJdmtRYjVJWHBMUHNGRjdidHZsaFU1dU9XRVpDMFxuQUZPS1BvOTBDSFlFQ0NYbDRpL0QwbkF0cTZLem9QOG1BZzRPc1Q5YUQ3S1dJdXJQdkZpZnJhZWh5SG1WNGpFM1xucE9tZVZZU3hTV05XN0tybUhQd3hSTUgwNTFnMlhCYnN0MXVqQTFGNmhRY3VrWTQ1Ulp1YXR5NnYvM1pBNm41cFxueW9sMVpvemE0d0tCZ0JoOFk1WUI2Y0dNdFZwTVNVR2dCajNIRFdNMkM5eDlLcjNaUm9WWnJaazZrbmxOaVM1UFxuQUMyVUpSaUYwZGM2dzBkMjdpSS92OFhKQnoyWmlZQWV4VWNaZWQ1d2x2cXl2ZVlnUTZ1ejNIOFpuc01DUVZ6UFxuTW5EVkUwSmNFMEhHMUhReU9ZLzFYd1FPcm96Tm9tMUNhWEgwcklOalYwVlhEaFF6OFdyR3FxT2JBb0dCQUxnMlxualR4NDdmZHNTdUsvVWhuZHhDVUZGUUhTUlVGeFNXNmprZ1I3NEh2RUdBL3RuamhPL2NmTHIvQ29nN3JDWE9ZTFxuaDNwVHdZdHNkNStJQXJ4bFRKYWppMVZ6YS90bFcvVFBJcmVvSE4ycnZCQVBpWnJVdnFtQzZVVThKMFl2MVdoUFxuR0Eyd2h4Nk5yKzlhZkYxbklxdnVnVlprVWM2bm93WVROblc2bU9xTkFvR0FUQnJwYVp1T0dxTHJpNGJLSGFmT1xuZW5aSk1jT0lkd1JuNWhrTzJIeXFwZmMwc1NjQjVZZW53OGpVQWhsL0k1MDlNRkFQMklCRzhBTnZ5OUNYTFhRNVxuOEhlUzVkejk0d0NDaDJrVUd2UFhqU0xpbFZNVDVPNzNWZlVjK2RUZFZuRlZwalA2WjZmUmkzRGJGVnJhMngwYVxuMGtlUFUyUkkrbzFtcFRVZTI5QlJlRnc9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAidGNpLXB1YnN1YkB0Y2ktbWljcm9zZXJ2aWNlcy0yNjIwMjIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTE0ODI2MzY5MzAwOTE1Mzg3NTI3IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS90Y2ktcHVic3ViJTQwdGNpLW1pY3Jvc2VydmljZXMtMjYyMDIyLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==
        subscriber:
          max-ack-extension-period: 3600
          executor-threads: 5
          parallel-pull-count: 5
          retry:
            max-rpc-timeout-seconds: 10
            max-attempts: 100
        publisher:
          executor-threads: 5
