
logging.level:
  root: INFO
  pe.net.tci.pse.comprobante.repository: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  #org.springframework.web: INFO
  #com.microsoft: ERROR

server:
  port: 7070

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: password
  flyway:
  enabled: true
  url: jdbc:mysql://localhost:3306/db01?allowPublicKeyRetrieval=false&useSSL=true&requireSSL=true&serverTimezone=UTC&encrypt=true&autoReconnect=true
  user: root
  password: password
  locations: classpath:db/migration
#schemas: dbo
#flyway-schemas: flyway-schemas
  group: false
  cloud:
    gcp:
      stream:
      bindings:
        procesadorDeclaracionOutput:
          destination: CLIENTE-TOPIC
          group: DECLARACION
        procesadorAuditoriaOutput:
          destination: AUDITORIA-TOPIC
          group: DECLARACION
        procesadorDeclaracionInput:
          destination: CLIENTE-TOPIC
          group: DECLARACION
        procesadorAuditoriaInput:
          destination: AUDITORIA-TOPIC
          group: DECLARACION    
      project-id: tci-microservices-262022
      credentials:
        encoded-key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAidGNpLW1pY3Jvc2VydmljZXMtMjYyMDIyIiwKICAicHJpdmF0ZV9rZXlfaWQiOiAiMWIxMGE0YjQ2OThjYTJjOGU0NTZlOWIxY2VjMjEwYzM3YTYxZGQ1MCIsCiAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZnSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2d3Z2dTa0FnRUFBb0lCQVFDY2RwSzlhR3pEUUtRSFxucjhjWG80STBIUjJOd2l2aCtHYUUrS3ZkN3ZHM21pZCt3WTJWZ2JlckY5ZWd6OFdURDMwUkVCTGJkQUNhRnZYQlxub2xvc3BQeVZTOVJmZjRvQm5tZ3A2SjlOeitSS2lXVHJuRjJjN3ZwTDhPQzM0bHlYMTBSQ29xZUd1aVd0TTB0c1xuRUk4RStlNGk5NGJEdjd2cXEzRWVlYUdxRG5YRDE5YitteHFzUDR1UDlPLzhta0dYWkN6RWdsajBadWwvOWRid1xuVTJLZGxKaVdHZGdkbUZPdlllbnhiZDVHWGw2bkxRMmVvak1mcjg3eStkMVlpVVFVUG9uNkxhL1FrVnp6Tm03ZFxubzVaR0RLQmZBVFZtcEJOZ1k1UzlyaDVyVEFnOSt1UnV0NERDUVlDNU50SkUxQ3BTUFNzWE1hNE1pZzQwVG5FRFxuWWxYWC9nR25BZ01CQUFFQ2dnRUFEMUkzSFZBSDhuaTJkMEE1dFRGZ014MDB3eWhqNXExTjBMQ1BGOXpwazRxSFxuV295MmdoRGhQT0pKVGFoNjF1TTU0bjFaODE1aEhyV24zQTI3V2NyUUp3aDFZK0tYejMvRkFIR1VnK2liR01kcVxuZC8zb1Z0RTU5a3pBbkpFUWN4Znp5Ymltd2ZVaGNsdm5BMDU5eXNWMGtieitWOVhESDRBcFJBd3lEZlo3aHJGSlxuVVRDeG8zTG5QeU5kSFNGNXpQell0Rk8xNjVrcTRJU1hsV2ZJdnF3TVovczdOeUovVHV6R0ZZOEllZ2ZSN0d5Rlxuc0pJNE9jUWxXWGFxTkdvVmZXZ1pkZUZwTGJqN1l5cWE2ZDIzRW9OS0kvdC90eE1SNitEVkxSNEE2aDIzSkZSblxuRjJ1NDBvMmZVS3dYTktuQm5LTmFlTG40WVQrdDlIeVduajEzVS9JRzhRS0JnUURSNkZvNUI4aldLZzMzUTIrNFxuY1lCVUp2MmV0Q2ZldkYvcWNPOHJ4RjBhd3FZZm1sdHJQM3BzTjFRZ0t1ZUU2SFNWbC8xZVRleTBtUzNzS3FPbFxuM09KSHFpN1MwS3FCbnEyVUtVWGFqWFdORzNMRVR6SmRBckV0TFdRd0l2TWdwZXdoS3FSRWFEaVk5TVRiRjRwTFxuOWZnU2xyOURkZnhncDBURFBwMHduNUh1OFFLQmdRQyswZXQ3VmlMZXVUQ285aXo5NCtlUmU1MVVrNTFpazVRQlxuUitpUSs5bXZWRldKRVZkQ0dGY2xQRkhlSXh5S0VyYU1yNHV3TGgxZkdURldqeFJrMm4yaUVrb1lYemI1S2FieVxuNWtqVk9PS0YxdmUrOUtyNTEvUFN6L2VzcUVLRC9BcmdaTEdEWXU3REdJbjhGK042UWlTS1U4cVhUQTRFMDEwZ1xuWExZVmQ0NHFGd0tCZ1FDUURtZEU5bnUxeHh6WWtqWnRIYkFWa01ERUZ4MjV0Z3daaURJTUZuSlRPRHpzT1hIK1xuRTQyQUVTU3lBdC9yRGVGYy9QZE1yaXdCOFpKYm54TzZjL0h6ZnU4dGpUbEhSZEFZZTQ3T0pBRUZ1MDJ6UGlyeFxuUERTK0xZV3hwM3ExOEVreXBlSWdkR3BMUnNpSEdBdTRmL0VsU01Hd21adC85YXV5VnhsbjBrdEQ4UUtCZ1FDTVxuSzAxc094akFQSTdtL25hTVJiWmI0czd1U3NUSW5abVIyMDJWK3Jxc0ZTb0QxcTRmU2h2eHFUNkdDNHF5VGc2MFxuaDFyNEh0ZktmSW9HaUhHMXA5MnppUFhPczFxQmFyeE5IeVlQSW9zYlA0NmJRY1M2Wkl5aHBjek1rb2pSeFBvRVxuWFZNY0xUY3dMcjFsWmZMZVl1bk9oc0NCcFFlRE9mUGxpdFRpTGdGTEh3S0JnSDRsM1FwdTJIaVFJTFJqRFNzQVxuRW5GeWhFR1lObElzcytWblM1NnE5UjBFRHVvQnRaTlVqcDU0b29GTHI1QWRiSTZZSFVOalpmQjQ1ak5xU1g0OFxubUo2NldOS1k2ZFpQbVpnVEREZUVoT3N3WGZjZmh3OFBRd3ZPV2sxOXdkMWNaYzVuSUt2TGpWblRsZXA1VmdLdVxuV3VMb1lyQ0gza1N0WXpNTE5PQ29ZTTFHXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLAogICJjbGllbnRfZW1haWwiOiAidGNpLXB1YnN1YkB0Y2ktbWljcm9zZXJ2aWNlcy0yNjIwMjIuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTE0ODI2MzY5MzAwOTE1Mzg3NTI3IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS90Y2ktcHVic3ViJTQwdGNpLW1pY3Jvc2VydmljZXMtMjYyMDIyLmlhbS5nc2VydmljZWFjY291bnQuY29tIgp9Cg==
        subscriber:
          max-ack-extension-period: 3600
          executor-threads: 5
          parallel-pull-count: 5
          retry:
            max-rpc-timeout-seconds: 10
            max-attempts: 100
        publisher:
          executor-threads: 5
