



logging.level:
  root: INFO
  com.example.lab01.repository: DEBUG
  org.springframework.jdbc.core: DEBUG
  org.springframework.jdbc.core.StatementCreatorUtils: DEBUG
  #org.springframework.web: INFO
  #com.microsoft: ERROR


server:
  port: 9999
  
lab02:
  cache:
    host: cache
    port: 6379
    enableSsl: false
    password: password
  event:
    host: bus
    port: 5672
    username: rabbitmq
    password: rabbitmq